services:
  mailer-go:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/khw315/mailer-go:latest
    container_name: mailer-go
    restart: unless-stopped
    ports:
      - "25:2525" # Host SMTP Port (25/587) -> Container (2525)
      - "8080:8080" # Healthcheck & Prometheus Metrics
    env_file:
      - .env
    volumes:
      - mailer-spool:/var/spool/mailer-go
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  mailer-spool:
